name: Antti Karppinen Digital Art
favicon: null
layout_spectrum: 0.06748050171881914
typography_spectrum: 0.9885053753387183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7856168146245182
  lightness: 0.8004842742811888
  saturation: 0.3183474421966821
  rhythmicContrast: 0.32523350045084953
purpose: []
